version: 2

models:
  - name: fct_stock_prices
    description: "Fact table for stock prices"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: trading_date
        description: "Date of the stock price"
        tests:
          - not_null
      - name: open
      - name: high
      - name: low
      - name: close
      - name: volume
